baseURL = 'https://rie03p.github.io/hugo-site/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-PaperMod'

# Use relative URLs for assets so the site works under a subpath on GitHub Pages
relativeURLs = true

[[menus.main]]
name = 'Blog'
url = '/posts/'
weight = 10
